name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm i -g snyk
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}
    - run: snyk monitor --org=github-dfl --sarif-file-output=snyk-oss.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk-oss.sarif
    #- name: install snyk-to-html
    #  run: |
    #    npm install snyk-to-html -g
    #    snyk test --json | snyk-to-html -o result.html
    #    mkdir downloads
    #    cp -v /home/runner/work/nodejs-goof/nodejs-goof/*.html /home/runner/work/nodejs-goof/nodejs-goof/downloads
    #- name: Use the Upload Artifact GitHub Action
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: results
    #    path: downloads
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
